name: Hugo

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: latest
          extended: true

      - name: Build
        run: hugo --minify

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: public
          path: public/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    if: >
      startsWith(github.ref, 'refs/heads/main')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2.0.8
        with:
          name: public
          path: public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/
          cname: pietermaene.be
